### PR TITLE
Invalidate HTTP GET method

### PR DESCRIPTION
**Pull request by chloe-zh**
*Issue #, if available:*

* #413 

*Description of changes:*

* removed http get method
* added integtest

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by penghuo** [comment]
Is there any doc need to be updated?

**Comment by zhongnansu** [comment]
> Is there any doc need to be updated?

I guess at least README also need to update

**Comment by abbashus** [comment]
Why is only POST request secure? 

Also the whole HTTP payload  (including HTTP verb , URL,  headers, body) is encrypted not just the body.

So in the absence of HTTPS, both GET and POST will reveal sensitive information, and in presence of HTTPS both GET and POST will equally hide the sensitive information, because the whole payload is encrypted.

Since this is a breaking change (client using GET requests will fail after this change), we should 
have a strong and valid case to make this change.

Please correct if I am wrong or missing something.

https://en.wikipedia.org/wiki/HTTPS

> Because HTTPS piggybacks HTTP entirely on top of TLS, the entirety of the underlying HTTP protocol can be encrypted. This includes the request URL (which particular web page was requested), query parameters, headers, and cookies (which often contain identity information about the user)

**Comment by chloe-zh** [comment]
> Is there any doc need to be updated?

Hi @penghuo @zhongnansu , thank you for the reminder. README and the reference manual are updated now. Thanks!

**Comment by chloe-zh** [comment]
> Why is only POST request secure?
> 
> Also the whole HTTP payload (including HTTP verb , URL, headers, body) is encrypted not just the body.
> 
> So in the absence of HTTPS, both GET and POST will reveal sensitive information, and in presence of HTTPS both GET and POST will equally hide the sensitive information, because the whole payload is encrypted.
> 
> Since this is a breaking change (client using GET requests will fail after this change), we should
> have a strong and valid case to make this change.
> 
> Please correct if I am wrong or missing something.
> 
> https://en.wikipedia.org/wiki/HTTPS
> 
> > Because HTTPS piggybacks HTTP entirely on top of TLS, the entirety of the underlying HTTP protocol can be encrypted. This includes the request URL (which particular web page was requested), query parameters, headers, and cookies (which often contain identity information about the user)

Thanks @abbashus  for raising your concerns. 
You're correct that both GET and POST on HTTPS are encrypted while on HTTP are revealing data. And we can encrypt the transmission using SSL/TSL. 
However, to my understanding, HTTP GET method might expose the info in the url to browser plugins or even like the browser history, and the server log etc. so that it gets the risk of leaking out data. But POST method passes the queries in request body, which is safe to use HTTP on SSL/TSL.

**Comment by abbashus** [comment]
@chloe-zh From browser point of view, it makes sense. But w.r.t to server, it not guaranteed, completely upto server what it wants to do with the HTTP payload.

**Pull request merged**
