### PR TITLE
changed ES version in build.gradle for 7.2 release

### PR DESCRIPTION
**Pull request by davidcui-amzn**
*Issue #, if available:*
#202 
*Description of changes:*
Changed build.gradle to use Elasticsearch 7.2.1 for OD release

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by davidcui-amzn** [comment]
Update: Ignore the empty unit test, git added on accident. Will remove in second commit

**Comment by dai-chen** [comment]
Could you change this file as well? Reference: https://github.com/opendistro-for-elasticsearch/sql/pull/91/files#diff-503f218d646c10f484fdc9d6315bf2e3R16. We need to figure out if this is useless or not later but please change it accordingly for now.

And because this is a minor ES version upgrade without no more changes, could you add release notes in this PR too? Reference: https://github.com/opendistro-for-elasticsearch/sql/pull/94/files

**Comment by dai-chen** [comment]
Also please create opendistro-1.2.1 branch in main SQL repo first. Then create your own branch from there, make code changes and send out PR based on it instead of master.

**Comment by davidcui-amzn** [comment]
Closing this PR since it merges to master and not opendistro-1.2.1

**Pull request closed without merging**
