### PR TITLE
Add Error Message for Explain and Run

### PR DESCRIPTION
**Pull request by davidcui-amzn**
*Issue #, if available:*
#863 
*Description of changes:*
* Added a generic error message in `Explain` for invalid queries. The error message consists of `<API Response>: this query is not explainable.`
* Added `this query is not runnable` to error messages for `Run` on invalid queries. 

Invalid `Explain` on SQL: 
Screen Shot 2020-12-01 at 12 25 09 PM

Invalid `Explain` on PPL: 
Screen Shot 2020-12-01 at 12 38 00 PM

Invalid `Run` on SQL: 
Screen Shot 2020-12-01 at 1 14 26 PM

Invalid `Run` on PPL: 
Screen Shot 2020-12-01 at 1 14 41 PM

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by joshuali925 — APPROVED** [review]
LGTM

**Comment by dai-chen** [comment]
Is there any chance to add UT for this change?

For Run error message, it would be more helpful to show the "reason" or "details" in message from backend if "status"=400.

**Comment by davidcui-amzn** [comment]
> Is there any chance to add UT for this change?
> 
> For Run error message, it would be more helpful to show the "reason" or "details" in message from backend if "status"=400.

Do you mean display the response code in the output as well? Also I can try to add some UTs to check output matching on invalid queries/Explain

**Comment by dai-chen** [comment]
> > Is there any chance to add UT for this change?
> > For Run error message, it would be more helpful to show the "reason" or "details" in message from backend if "status"=400.
> 
> Do you mean display the response code in the output as well? Also I can try to add some UTs to check output matching on invalid queries/Explain

I meant when the "status" as below is 400, the words in "reason" or "details" would help user figure out why:

```
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Failed to parse query due to offending symbol [60] at: '\n         SELECT ((YEAR(DATE_ADD(FROM_DAYS(FLOOR(NULL) + 693961), INTERVAL 60' <--- HERE... More details: Expecting tokens in {'SELECT', '('}",
    "type": "SyntaxAnalysisException"
  },
  "status": 400
}
```

**Comment by davidcui-amzn** [comment]
Added more detailed error output for `Run` on invalid queries to include API response.

SQL example: 
Screen Shot 2020-12-01 at 4 12 53 PM

PPL example:
Screen Shot 2020-12-01 at 4 18 32 PM

**Comment by chloe-zh** [comment]
> Added more detailed error output for `Run` on invalid queries to include API response.
> 
> 
> 
> SQL example: 
> 
> Screen Shot 2020-12-01 at 4 12 53 PM
> 
> 
> 
> PPL example:
> 
> Screen Shot 2020-12-01 at 4 18 32 PM
> 
> 
> 
> 

This looks good enough, but I wonder would it be better if the error reason, detail, type and status are parsed and displayed into a paragraph than put the raw exception to the console log, since the output panel looks not a json style but only a plain text box. For example:

```
SHOW TABLES LIKE: Bad request, this query is not explainable.

reason: "Invalid SQL query"
details: "Expected syntax example: 'SHOW TABLES LIKE <table pattern>'"
type: "IllegalArgumentException"
status: 400
```

**Comment by davidcui-amzn** [comment]
> > Added more detailed error output for `Run` on invalid queries to include API response.
> > SQL example:
> > Screen Shot 2020-12-01 at 4 12 53 PM
> > PPL example:
> > Screen Shot 2020-12-01 at 4 18 32 PM
> 
> This looks good enough, but I wonder would it be better if the error reason, detail, type and status are parsed and displayed into a paragraph than put the raw exception to the console log, since the output panel looks not a json style but only a plain text box. For example:
> 
> ```
> SHOW TABLES LIKE: Bad request, this query is not explainable.
> 
> reason: "Invalid SQL query"
> details: "Expected syntax example: 'SHOW TABLES LIKE <table pattern>'"
> type: "IllegalArgumentException"
> status: 400
> ```

I like this idea, will add that

**Review by chloe-zh — APPROVED** [review]
LGTM, thanks for the changes!

**Pull request merged**
