### PR TITLE
ODBC: Adding Power BI M connector 

### PR DESCRIPTION
**Pull request by rupal-bq**
*Issue #595*

*Description of changes:*
* Connects to Open Distro For Elasticsearch with No authentication & No SSL only.
* Added icons with all required sizes.

image

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by biuserissue** [comment]
hello,
can you please guide me from where can I download this beta version . I cant find it on the official website of distro   
image

**Comment by anirudha** [comment]
https://github.com/opendistro-for-elasticsearch/sql/blob/develop/sql-odbc/docs/user/power_bi_support.md

It's part of the odbc connector

On Wed, Feb 17, 2021 at 00:35 biuserissue <notifications@github.com> wrote:

> hello,
> can you please guide me from where can I download this beta version . I
> cant find it on the official website of distro
> [image: image]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_79192631_108177320-2De59d8880-2D7124-2D11eb-2D8714-2Dd5b71ade0feb.png&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=RKcsd4bftifYB5-k8gn80w&m=vATIdIAknO6Q4QchJ2PWPZnsRv45a9C-GqxdqxKYb8U&s=s6FzN9fPr7eMP5C_sK4vinDAE_nO9RppPJL5NtZB-CM&e=>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_opendistro-2Dfor-2Delasticsearch_sql_pull_596-23issuecomment-2D780394492&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=RKcsd4bftifYB5-k8gn80w&m=vATIdIAknO6Q4QchJ2PWPZnsRv45a9C-GqxdqxKYb8U&s=Ap8sM8u4qcNZP7U_P9gdp4bK-4jP7gCP2SXzZilWzp0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAAEXISWH42NSHBRD3B53KTS7N5UHANCNFSM4PB2FYJQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=RKcsd4bftifYB5-k8gn80w&m=vATIdIAknO6Q4QchJ2PWPZnsRv45a9C-GqxdqxKYb8U&s=JThaCdkfv1wpb_T6armhOR_CNICEgilKmLk6mIdssFU&e=>
> .
>
-- 
Anirudha P. Jadhav

**Comment by anirudha** [comment]
https://github.com/opendistro-for-elasticsearch/sql/blob/develop/sql-odbc/docs/user/power_bi_support.md

It's part of the odbc connector

**Comment by biuserissue** [comment]
followed the steps 
made a folder in user > documents >  Power BI Desktop\Custom Connectors\
still the Distor driver is unable to connect

**Pull request merged**
