### PR TITLE
Update new engine release doc

### PR DESCRIPTION
**Pull request by dai-chen**
*Issue #, if available:* https://github.com/opendistro-for-elasticsearch/sql/issues/1051

*Description of changes:*

1. Updated README section title and release notes for upcoming release: https://github.com/dai-chen/sql/blob/update-new-engine-doc/docs/dev/NewSQLEngine.md
2. Added doc for SQL comment support which was undocumented earlier: https://github.com/dai-chen/sql/blob/update-new-engine-doc/docs/user/general/comments.rst
3. Renamed "SQL Workbench" to "Query Workbench"

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by chloe-zh** [comment]
Not a problem of this PR, but could you change the workbench name from "SQL Workbench" to "Query Workbench" in the readme.md files?

**Review by chloe-zh — APPROVED** [review]
LGTM, thanks for the updates!

**Comment by dai-chen** [comment]
> Not a problem of this PR, but could you change the workbench name from "SQL Workbench" to "Query Workbench" in the readme.md files?

Sure. Changed both in README and workbench/README.

**Review by penghuo — APPROVED** [review]
LGTM

**Pull request merged**
