### PR TITLE
Fix Round fix issue when input is negative and end with .5

### PR DESCRIPTION
**Pull request by harold-wang**
*Issue #908 
Round function did not round negative number correctly in case input is negative and end with .5. 
issue: Round(-3.5) = 3.0 instead of 4.0

*Description of changes:*
Change Round(double) to Round(double, 0)

Test: IT added and 100% pass

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by penghuo — APPROVED** [review]
Thanks for the change.

**Comment by penghuo** [comment]
Is it related to any open issue? if so, please also link it.

**Review by dai-chen — APPROVED** [review]
Thanks for the fix!

**Review by chloe-zh — APPROVED** [review]

**Comment by harold-wang** [comment]
> Is it related to any open issue? if so, please also link it.

Linked, thanks

**Pull request closed without merging**
