### PR TITLE
add string function RIGHT

### PR DESCRIPTION
**Pull request by rupal-bq**
*Description of changes:*
- Added string function RIGHT().
- Added unit test.
- Added manual IT because the comparison test didn't work.
- Updated doc.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by dai-chen — APPROVED** [review]
Thanks for the changes! Could you check if we can add comparison test now? https://github.com/opendistro-for-elasticsearch/sql/tree/develop/integ-test/src/test/resources/correctness/expressions

I recall there was some issue adding text function. I think it's doable now?

**Comment by penghuo** [comment]
could you also add the doc for PPL? https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/experiment/ppl/functions/string.rst

**Review by chloe-zh — APPROVED** [review]

**Comment by rupal-bq** [comment]
> Thanks for the changes! Could you check if we can add comparison test now? https://github.com/opendistro-for-elasticsearch/sql/tree/develop/integ-test/src/test/resources/correctness/expressions
> 
> I recall there was some issue adding text function. I think it's doable now?

Thanks. added comparison test.

**Comment by rupal-bq** [comment]
> could you also add the doc for PPL? https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/experiment/ppl/functions/string.rst

Thanks. added this change.

**Pull request merged**
